### ISSUE TITLE
Documentation of the Framework

### ISSUE THREAD

**Issue by mastermind1981** [CJSCommonPlatform/microservice_framework#207]
Hi,

First, I want to congratulate you for the job you are doing and I hope you will get sooner an RC.

Could you please add some docs about the framework and explain why have you created it?

By the way the use of the JSon enveloppe is very interesting .

Regards,

**Comment by purple52** [comment]
Thanks! Documentation is ongoing, pending some further changes to the structure of the framework.

The premise of the framework is to provide a mechanising for separating business code from plumbing; a way of implementing the ports and adapters architectural pattern. Adapters can then be generated from RAML specifications of REST and JMS interfaces. It also provides a suite of composable services for implementing CQRS patterns and event sourcing. There is a talk I did a while ago available on the ideas behind it: https://youtu.be/6s24mDe30bA
