### ISSUE TITLE
Auto reconciling viewstore

### ISSUE THREAD

**Issue by gogit** [CJSCommonPlatform/microservice_framework#210]
The decoupled nature of the architecture (for scalability) could lead to the viewstore being out of sync with the eventstore. 
For example the listeners are down and the viewstore has not received all the events to build a consistent view.
Devops could manually intervene to sync the viewstore with the event store.

An additional option from an availability perspective is to have a viewstore that reconciles automatically with the eventstore. 

**Setup**
- Eventstore - has the last n events (by id, date).
- Viewstore - has a setup that stores the last n received events (by id, date)
- New component - Compares the 2 sets, if they are out of sync, rinses and rebuilds the viewstore.

**Comment by purple52** [comment]
Event API for pulling events instead of them being pushed is planned on the backlog.
